items:
  # Custom Texturepack
  # url para download do datapack base
  use-custom-textures: false

  soul-egg:
    display-name: "<white>Soul Egg"
    lore:
      - "<aqua>{petname} pet soul"
  charged-soul-egg:
    display-name: "<aqua><bold>Charged Soul Egg"
    lore:
      - "<aqua>{petname} pet soul"

achievements:


config:
  # Custom Texturepack
  # url para download do datapack base
  use-custom-textures: true

localization:
  # Soul Egg
  soul-egg: "<white>Soul Egg"
  charged-soul-egg: "<aqua>Charged Soul Egg"
  soul-egg-lore: "<grey>Pet: {petname}"

  # Command usage and help (CLI)
  command-reload-output: "Reload configuration data"
  command-reload-description: "Reload configuration data"
