config:
  # Custom Texturepack
  # url para download do datapack base
  use-custom-textures: false

localization:
  # Soul Egg
  soul-egg: "<white>Soul Egg"
  charged-soul-egg: "<aqua>Charged Soul Egg"
  soul-egg-lore: "<grey>Pet: {petname}"

  # Command usage and help (CLI)
  command-reload-output: "Reload configuration data"
  command-reload-description: "Reload configuration data"
