name: Build Paper Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ShadowJar
        run: ./gradlew shadowJar

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-build
          path: build/libs/*.jar